# Generated by Django 2.0.2 on 2018-02-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazdy',
            name='bateries',
        ),
        migrations.AddField(
            model_name='baterie',
            name='inpojazd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baterie', to='pojazdy.Pojazdy'),
        ),
    ]
